#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ ! -d constant/polyMesh/ ]; then
    MESHDIR="../fluent-reference"
    runApplication fluent3DMeshToFoam -scale 0.001 "${MESHDIR}/pipe.msh"
    runApplication checkMesh

    mkdir logs/
    mv log.* logs/
else
    echo "Mesh already there..."
fi

runApplication decomposePar

runParallel $(getApplication) &

# After running
# reconstructPar -latestTime

#------------------------------------------------------------------------------
