#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ ! -d constant/polyMesh/ ]; then
    /usr/bin/gmsh wedge.geo -3 -format msh2 > log.gmsh
    runApplication gmshToFoam wedge.msh
    rm -rf wedge.msh

    pip install PyFoam
    pyFoamChangeBoundaryType.py . front wedge
    pyFoamChangeBoundaryType.py . back  wedge
    pyFoamChangeBoundaryType.py . wall  wall
    
    runApplication checkMesh

    mkdir logs/
    mv log.* logs/
else
    echo "Mesh already there..."
fi

runApplication $(getApplication) &

#------------------------------------------------------------------------------
